### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Basti10** [Automattic/Genericons#72]
hello
I would like to divide the CSS into two parts.
The first part should be only for Internet Explorer and the second part for all modern browsers.
Can you please tell me which CSS is for Internet Explorer 9 and below and which CSS Code is for all modern browsers?
Thanks in advance!

**Comment by jasmussen** [comment]
I wish that were possible, but unfortunately the reality is rather muddled. 

Old versions of Internet Explorer use .eot fonts. Newer IEs, as well as modern browsers use WOFF. Older mobile Safaris use SVG, and I can't even recall which browsers use .TTF.

But there's only one `@font-face` declaration. So in order to serve the right font to the right browser, we rely on an elaborate hack called "the bulletproof font-face syntax". Read more about it here: http://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/

The long and short of it is: we can't change that syntax at all, without breaking support for some browsers. Sorry!
