### ISSUE TITLE
Instagram icon needs to be updated

### ISSUE THREAD

**Issue by JakePT** [Automattic/Genericons#95]
So Instagram's updated their icon:
http://www.theverge.com/2016/5/11/11656252/instagram-redesigns-icon-app

Genericons' version is now the old icon, obviously.

Would be nice if the icon could be updated to the new one, or the new one added. I have a lot of clients out there with Genericons social menus built with [this method](http://justintadlock.com/archives/2013/08/14/social-nav-menus-part-2) and have already had a couple requesting an update. Will be a lot easier if the font itself is updated.

If there's no plans to update then it would also be good to know that as soon as possible so other arrangements can be made.

**Comment by jasmussen** [comment]
Good ticket, thanks for asking. Genericons is moving towards having no social logos at all (<a href="https://github.com/Automattic/Genericons/tree/refactor/genericons">see a sneak peek</a>), where the current release of Genericons will be bundled as "classic". I think it makes sense to update the Instagram icon just for that "classic" release. 

Instead of relying on Genericons for social logos, I'd recommend everyone adopt <a href="https://github.com/Automattic/social-logos">Social Logos</a> at this point. It comes with SVGs, icon fonts, an SVG sprite and a grunt build process.

**Comment by JakePT** [comment]
Ok makes sense. I'm looking to use some sort of SVG sprite solution going forward, but it'd be nice to have a drop-in solution for these existing sites.

I assume Social Logos will be getting updated with the new icon soon? And that requests for new icons would be considered?

**Comment by jasmussen** [comment]
> I assume Social Logos will be getting updated with the new icon soon? And that requests for new icons would be considered?

I'll open a ticket right now. And yes, I think that repo will be much more welcoming to additions.

**Comment by volthemes** [comment]
bump :D

**Comment by Ipstenu** [comment]
@volthemes - As Joen said, you should go to https://github.com/Automattic/social-logos and open a ticket there.

Genericons is removing social media icons.
